### PR TITLE
TEP-0115: Update git resolver doc to use "revision" and "pathInRepo" fields

### PR DESCRIPTION
**Pull request by QuanZhang-William**
Part of TEP-0115

Update Git Resolver documentation to use "revision" and "pathInRepo" fields to reflect the changes in [TEP-0115: Add git revision resolution support in Git Resolver](tektoncd/resolution#75) and [Add core Reconciler testing and fake resolver framework functions](tektoncd/resolution#51)

### CODE REVIEW

**Review by jerop — APPROVED** [review]
thanks @QuanZhang-William!

**Comment by jerop** [comment]
@abayer I'm not an owner in this repo so can't approve, switch places? 😂 

/lgtm

**Comment by abayer** [comment]
/approve

=)

**Pull request merged**
